#!/usr/bin/env sh
# pretty good build command

# on my system (openbsd) cc is a clang
# on most linux systems, it is gcc
# either way, there should be some kind of symlink called "cc"
CC=$(which cc || which clang || which gcc)

CFLAGS=-Wall -Wextra -pedantic -g -std=c99
LDFLAGS=-static

$CC $CFLAGS $@ $LDFLAGS
